In [1]:
import numpy as np
import pandas as pd

from Node import Node
from DecisionTreeClassifier import DecisionTreeClassifier

# Get the data

In [2]:
col_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'type']
data = pd.read_csv("iris.csv", skiprows = 1, header = None, names = col_names)
data.index = range(data.shape[0])
data["type"] = data["type"].astype("category").cat.codes
data.head(10)

   sepal_length  sepal_width  petal_length  petal_width  type
0           5.1          3.5           1.4          0.2     0
1           4.9          3.0           1.4          0.2     0
2           4.7          3.2           1.3          0.2     0
3           4.6          3.1           1.5          0.2     0
4           5.0          3.6           1.4          0.2     0
5           5.4          3.9           1.7          0.4     0
6           4.6          3.4           1.4          0.3     0
7           5.0          3.4           1.5          0.2     0
8           4.4          2.9           1.4          0.2     0
9           4.9          3.1           1.5          0.1     0

# Train-Test Split

In [27]:
X = data.iloc[:, :-1].values
Y = data.iloc[:, -1].values.reshape(-1,1)
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .2, random_state = 41)

# Fit the model

In [29]:
classifier = DecisionTreeClassifier(min_samples_split = 3, max_depth = 3)
classifier.fit(X_train, Y_train)
classifier.print_tree()

X_2 <= 1.9 ? 0.33741385372714494
 left:0.0
 right:X_3 <= 1.5 ? 0.427106638180289
  left:X_2 <= 4.9 ? 0.05124653739612173
    left:1.0
    right:2.0
  right:X_2 <= 5.0 ? 0.019631171921475288
    left:X_1 <= 2.8 ? 0.20833333333333334
        left:2.0
        right:1.0
    right:2.0

# Test the model

In [30]:
Y_pred = classifier.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_pred)

0.9333333333333333

In [38]:
pd.DataFrame(np.concatenate((X_test, Y_test), axis=1))

      0    1    2    3    4
0   6.0  2.2  5.0  1.5  2.0
1   6.4  2.8  5.6  2.1  2.0
2   7.7  3.0  6.1  2.3  2.0
3   6.1  3.0  4.6  1.4  1.0
4   6.8  3.0  5.5  2.1  2.0
5   6.1  2.8  4.0  1.3  1.0
6   6.3  2.7  4.9  1.8  2.0
7   6.0  3.4  4.5  1.6  1.0
8   6.5  3.0  5.2  2.0  2.0
9   6.8  3.2  5.9  2.3  2.0
10  6.1  3.0  4.9  1.8  2.0
11  5.1  3.4  1.5  0.2  0.0
12  4.4  3.0  1.3  0.2  0.0
13  5.0  2.3  3.3  1.0  1.0
14  5.1  3.3  1.7  0.5  0.0
15  6.3  2.8  5.1  1.5  2.0
16  4.8  3.1  1.6  0.2  0.0
17  6.0  2.7  5.1  1.6  1.0
18  4.9  3.1  1.5  0.1  0.0
19  4.5  2.3  1.3  0.3  0.0
20  5.5  2.4  3.7  1.0  1.0
21  6.9  3.2  5.7  2.3  2.0
22  5.0  3.5  1.6  0.6  0.0
23  4.7  3.2  1.3  0.2  0.0
24  5.6  2.9  3.6  1.3  1.0
25  6.0  2.2  4.0  1.0  1.0
26  6.3  3.3  4.7  1.6  1.0
27  5.8  2.7  4.1  1.0  1.0
28  5.0  3.3  1.4  0.2  0.0
29  6.1  2.9  4.7  1.4  1.0